version: '2'

services:
    med_records-db:
        image: mongo
        ports:
            - 8081:8081
        volumes:
            - '.:/home'
    gateway-db:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - '.:/home'
    gateway: 
        extends:
            file: docker-template.yml
            service: base
        command: make rungateway
        volumes:
            - .:/code
        ports:
            - 3333:3333
        environment: 
            - APP=gateway
    med-records:
        extends:
            file: docker-template.yml
            service: base
        command: make runmedrecords
        volumes:
            - .:/code
        ports:
            - 4444:4444
        environment: 
            - APP=med_records
