version: '2'

services:
    med_records_db:
        image: postgres
        ports:
            - 6432:5432
        volumes:
            - '.:/home'
        environment:
            - POSTGRESS_USER=medrecords
            - POSTGRESS_PASSWORD=devpass
            - POSTGRES_DB=med_records_db
    gateway_db:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - '.:/home'
        environment:
            - POSTGRESS_USER=gatewaey
            - POSTGRESS_PASSWORD=devpass
            - POSTGRES_DB=gateway_db
    gateway: 
        extends:
            file: docker-template.yml
            service: base
        command: make rungateway
        volumes:
            - .:/code
        ports:
            - 3333:3333
        environment: 
            - DJANGO_CONFIGURATION=Gateway
            - DJANGO_SETTINGS_MODULE=settings
            - POSTGRESS_USER=gatewaey
            - POSTGRESS_PASSWORD=devpass
            - DB_NAME=gateway_db
    med_records:
        extends:
            file: docker-template.yml
            service: base
        command: make runmedrecords
        volumes:
            - .:/code
        ports:
            - 4444:4444
        environment: 
            - DJANGO_CONFIGURATION=Medrecords
            - DJANGO_SETTINGS_MODULE=settings
            - POSTGRESS_USER=medrecords
            - POSTGRESS_PASSWORD=devpass
            - DB_NAME=med_records_db
