version: '2'

services:
    statistics_db:
        image: postgres
        ports:
            - 8432:5432
        volumes:
            - '.:/home'
        environment:
            - POSTGRES_USER=statistics
            - POSTGRES_PASSWORD=devpass
            - POSTGRES_DB=statistics_db
    mhealth_db:
        image: postgres
        ports:
            - 7432:5432
        volumes:
            - '.:/home'
        environment:
            - POSTGRES_USER=mhealth
            - POSTGRES_PASSWORD=devpass
            - POSTGRES_DB=mhealth_db
    med_records_db:
        image: postgres
        ports:
            - 6432:5432
        volumes:
            - '.:/home'
        environment:
            - POSTGRES_USER=medrecords
            - POSTGRES_PASSWORD=devpass
            - POSTGRES_DB=med_records_db
    gateway_db:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - '.:/home'
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=devpass
            - POSTGRES_DB=gateway_db
    gateway: 
        extends:
            file: docker-template.yml
            service: base
        command: make rungateway
        volumes:
            - .:/code
        links:
            - gateway_db
        ports:
            - 3333:3333
        environment: 
            - DJANGO_CONFIGURATION=Gateway
            - DJANGO_SETTINGS_MODULE=settings
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=devpass
            - DB_NAME=gateway_db
    med_records:
        extends:
            file: docker-template.yml
            service: base
        command: make runmedrecords
        volumes:
            - .:/code
        ports:
            - 4444:4444
        links:
            - med_records_db
        environment: 
            - DJANGO_CONFIGURATION=Medrecords
            - DJANGO_SETTINGS_MODULE=settings
            - POSTGRES_USER=medrecords
            - POSTGRES_PASSWORD=devpass
            - DB_NAME=med_records_db
    mhealth:
        extends:
            file: docker-template.yml
            service: base
        command: make runmhealth
        volumes:
            - .:/code
        ports:
            - 5555:5555
        links:
            - mhealth_db
        environment: 
            - DJANGO_CONFIGURATION=Mhealth
            - DJANGO_SETTINGS_MODULE=settings
            - POSTGRES_USER=mhealth
            - POSTGRES_PASSWORD=devpass
            - DB_NAME=mhealth_db
    statistics:
        extends:
            file: docker-template.yml
            service: base
        command: make runstatistics
        volumes:
            - .:/code
        ports:
            - 6666:6666
        links:
            - statistics_db
        environment: 
            - DJANGO_CONFIGURATION=Statistics
            - DJANGO_SETTINGS_MODULE=settings
            - POSTGRES_USER=statistics
            - POSTGRES_PASSWORD=devpass
            - DB_NAME=statistics_db
