# Generated by Django 2.2.6 on 2019-10-27 15:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('birth_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('problems_summary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('diagnostic', models.CharField(max_length=1000)),
                ('initial_planning', models.CharField(max_length=1000)),
                ('consult_notes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('medical_recomendations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('summary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('family_background', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('toxic_habits', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
