# Generated by Django 2.2.6 on 2019-10-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Medrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Medrecords.Patient'),
            preserve_default=False,
        ),
    ]
